### ISSUE TITLE
Release v1

### ISSUE THREAD

**Issue by mszostok** [mszostok/codeowners-validator#116]
**Description**

This tool was created a long time ago, and I already got a lot of feedback.

I plan to release the v1 once:
- [bugs](https://github.com/mszostok/codeowners-validator/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0.0+label%3Abug) will be fixed.
- [enhancements](https://github.com/mszostok/codeowners-validator/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0.0+label%3Aenhancement):
  - New checks:
    - https://github.com/mszostok/codeowners-validator/issues/94 
  - UX:
    - https://github.com/mszostok/codeowners-validator/issues/16 && https://github.com/mszostok/codeowners-validator/issues/73
      - This is important as this will change the way how codeowners is configured. It will give users a lot of freedom for customization with sensible defaults. Here we will move away from environment variables, and instead we will introduce support for YAML files configuration. Format it not yet defined, but to give you the overall idea, see:
      ```yaml
      # config.yaml
      
      # all available settings of specific linters
      checks-settings:
      
        owner:
          # The owner and repository name separated by slash. Used to check if GitHub owner is in the given organization.
          # (required)
          repository: "gh-codeowners/codeowners-samples"
      
          # Excluding configuration
          exclude-rules: # support excluded only for some users so outside collaborators are not check but the rest are validated
      
            # excluded for all as no owners provided
            - rule: valid-definition
            - rule: has-github-account
            - rule: team-exists
      
      
            # excluded only for a given owners
            - rule: is-in-organization
              owners:
                - @owner1
                - @owner2
                - @owner3
      ```
    - https://github.com/mszostok/codeowners-validator/issues/50. In general, documentation will be moved to a dedicated website with more readable interface.
    - https://github.com/mszostok/codeowners-validator/issues/61
  
  Other:
   - #49 to ensure no regression on v1.

Additionally, I would like to:
- add an option to format CODEOWNERS files. 
- and an option to **add/remove** a given owner from CODEOWNERS files and create related PRs automatically. For example, with such (draft) config:
    ```yaml
    updateRepositories:
      - path: "/tmp/cloned/repository" # local repository
      - url: "capactio/capact" # clone to temp dir
      - url: "capactio/website" # clone to temp dir
    
    insert:
      - owners: [ "@hakuna", "@matata" ]
        condition:
          pattern: "*.go"
      - owners: [ "@baz", "@bar" ]
        condition:
          associatedWithOwner: "@ghost"
    
    pullRequest:
      titleFormat: "Add {{ .NewOwner }} as a code owner in {{ .RepoName }}"
    ```
   Pull requests will be created in dedicated repositories.

As a result, maybe this project will be changed to  `codeowners-manager` as the spectrum of responsibilities will be much wider.
