### ISSUE TITLE
Team does not belong to organization

### ISSUE THREAD

**Issue by foolioo** [mszostok/codeowners-validator#121]
**Description**

Upgrading to version 0.7.0 makes the Github action fail, whereas version 0.6.0 passed. The action is configured as follows

```yaml
- name: CODEOWNERS validator
  uses: mszostok/codeowners-validator@v0.7.0
  with:
    checks: files,duppatterns,syntax,owners
    experimental_checks: notowned
    github_access_token: ${{ secrets.GITHUB_PAT }}
```

With a CODEOWNERS file that looks like so

```shell
* @org/team
```

**Expected result**

The action should not fail

**Actual result**

The action fails with the following message

```shell
[err] line 1: Team "@org/team" does not belong to "Org" organization.
```

**Steps to reproduce**

Since the issue relates to Github organization, unable to share a repository for reproduction

**Troubleshooting**

- [Read the release notes](https://github.com/mszostok/codeowners-validator/releases/tag/v0.7.0)
- Verified that the team exists
- Verified that the action passes when changing only the version back to 0.6.0

Is this a bug in version 0.7.0?
Is something missing in the action configuration?
